apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bv45eemek-python 
  janus-idp.io/tekton: bv45eemek-python
  backstage.io/kubernetes-id: bv45eemek-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bv45eemek-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  