apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bv45eemek-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bv45eemek-python 
  name: bv45eemek-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bv45eemek-python 
